### ISSUE TITLE
.NET 4.5.2 on XP x64 SP2 won't install

### ISSUE THREAD

**Issue by r3muxd** [Skulltrail192/One-Core-Api#28]
On .NET 4.5.2 on XP x64 SP2, with all updates installed, I am unable to install .NET 4.5.2. I get "The .NET Framework 4.5.2 is not supported on this operating system." regardless of compatibility settings on the extracted setup.exe or the sfx extractor. If I modify the ParameterInfo.xml to force it to install anyway, it installs, but wipes out all .NET installs on the system (i.e. no mscor*.dll).

**Comment by Skulltrail192** [comment]
Well, you need install AppComapt installer to set compatbility with WIndows Vista SP2 or above. Remember: you will receive a warning talking about missing Trusted installer service, only ignore. Or..You can do what you see on: https://www.youtube.com/watch?v=j5hTYGyLJkU. If you want ignore the warning, just install .net 2.0 and 3.5 (maybe only 2.0 working) befora 4.5 or above, it will prevent a error (i think 0x80000135) because without trusted installer, setup installation don't copy some dlls to system32.

**Comment by Skulltrail192** [comment]
And..With new version 2.0 .net Framework until lastest version (4.8) work on XP/2003/x64

**Comment by Skulltrail192** [comment]
Now, you can install .net Framework 4.8 using alternative installer created by https://github.com/abbodi1406/dotNetFx4xW7
You can see instructions on One-Core-API Binaries;
