### ISSUE TITLE
Step to Install DotNet 4.8 on XP

### ISSUE THREAD

**Issue by ghostplant** [Skulltrail192/One-Core-Api#54]
I follow this step to install dotnet 4.8 on XP:
(1) Install OneCore API and reboot;
(2) Install Official dotnet 4.8 without reporting errors, and system files are verified existing in C:\Windows\Microsoft.Net\4.0\xxx
(3) I run a certain dotnet 4.8 based executable, it still reports as a not recognized Win32 application.

What's wrong with it?

**Comment by jonm58** [comment]
You should use a third party to pack a dotnet4.8
this:https://github.com/abbodi1406/dotNetFx4xW7

**Comment by ghostplant** [comment]
Is there any packed verson?

**Comment by ghostplant** [comment]
Is there any packed verson?

**Comment by jonm58** [comment]
It's mine packed
https://mega.nz/file/ANAl2DKD#INurzFEEFUGxuHv4mX2xJlrUhx_c7pJG2_ogBaONx4w

**Comment by ghostplant** [comment]
> It's mine packed https://mega.nz/file/ANAl2DKD#INurzFEEFUGxuHv4mX2xJlrUhx_c7pJG2_ogBaONx4w

Thanks, the installation completes as well. But those related applications still cannot run successfully:
![e](https://user-images.githubusercontent.com/12099308/213904124-1dddd1be-7b46-42c3-a148-c4aab489fe00.png)

**Comment by Skulltrail192** [comment]
Well, .Net Framework 4.5+ has a issue. The installer depends of Windows Module Installer Service, only present on Vista+. So, because this service is missing, it's not copy some files on System32 (mscoree is the main file) and don't recognize .net 4.0+ is installed. So, you must install .Net 4.0 on XP/2003 before 4.5+ and it will be solved.
